#version: '4'
services:
  bot:
    build:
      context: .
    image: wrl-bot-image
    container_name: wrl-bot-container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      #- TZ=Europe/Moscow
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wrlbot
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
  db:
    image: postgres:12.0
    container_name: wrl-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wrlbot
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data



